version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.eirslett:frontend-maven-plugin
    versions:
    - 1.11.0
    - 1.11.2
  - dependency-name: com.helger.maven:ph-schematron-maven-plugin
    versions:
    - 6.0.2
    - 6.0.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  groups:
    actions:
      patterns:
      - "gulp*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    actions:
      patterns:
      - "*"
