language: java

jdk:
  - oraclejdk8
  - oraclejdk11

services:
  - docker

env:
  - img=existdb/existdb:latest
  - img=existdb/existdb:release

before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img

install:
  - mvn clean package

before_script:
  - docker cp ./target/exist-documentation-*.xar exist-ci:exist/autodeploy
  - docker start exist-ci
  # exist needs time
  - sleep 30

script:
  - mvn validate

after_success:
  - docker ps

notifications:
  hipchat: ec8fcfa661addc56a361a8ef536320@integrations
