language: java

jdk:
  - oraclejdk8
  - oraclejdk11

services:
  - docker

env:
  - img=existdb/existdb:latest
  - img=existdb/existdb:release

cache:
  directories:
  - $HOME/.m2

before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img

install:
  - mvn clean package -DskipTests -q

before_script:
  - docker cp ./target/exist-documentation-*.xar exist-ci:exist/autodeploy
  - docker start exist-ci
  # exist needs time
  - sleep 30

script:
  - mvn validate
  - mvn test
  - npm run cypress -- --record --key $CYPRESS_KEY

after_success:
  - docker ps

notifications:
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX
